### Take Away Points
- NumPy Arrays are **mutable**

In [36]:
import numpy as np

In [37]:
a1 = np.array([1,2,3,4,5])
print(a1)
# Access by indexing
print(a1[3])
# Access by -ve indexing
print(a1[-1])

[1 2 3 4 5]
4
5


In [38]:
# Modify an array element
a1[4] = 60
print(a1)
a1[-5] = 100
print(a1)

[ 1  2  3  4 60]
[100   2   3   4  60]


In [39]:
# Accesing/Modifying rank 2 (i.e 2D) Arrays --> [row,column]
d = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(d)
# 2 row 3 element
print(d[1,2])
d[2,1] = 100
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
6
[[  1   2   3]
 [  4   5   6]
 [  7 100   9]]


In [41]:
# Deleting the elements np.delete(ndarray, element_indexes, axis)
print(a1)
#delete 1st and last element
b1 = np.delete(a1, [0,4])
print(a1)
print(b1)

[100   2   3   4  60]
[100   2   3   4  60]
[2 3 4]


In [46]:
# Deleting from 2 D arrays
print(d)
dl = np.delete(d, [0,2], 0)
print(dl)
dl2 = np.delete(d, [0,2], 1)
print(dl2)

[[  1   2   3]
 [  4   5   6]
 [  7 100   9]]
[[4 5 6]]
[[  2]
 [  5]
 [100]]


In [51]:
# Append to arrays 1 D
print(a1)
a2 = np.append(a1, [20])
print(a2)
a3 = np.append(a1, [40, 80])
print(a3)

[100   2   3   4  60  20]
[100   2   3   4  60  20  20]
[100   2   3   4  60  20  40  80]


In [65]:
# Append to Rank 2 Arrays
print(d)
d1 = np.append(d, [[400, 200, 40], [200, 300, 800]], 0)
print(d1)
# Not clear how I can add multiple columns
d1 = np.append(d, [[400], [200], [40]], 1)
print(d1)

[[  1   2   3]
 [  4   5   6]
 [  7 100   9]]
[[  1   2   3]
 [  4   5   6]
 [  7 100   9]
 [400 200  40]
 [200 300 800]]
[[  1   2   3 400]
 [  4   5   6 200]
 [  7 100   9  40]]


In [69]:
# Inserting elements in middle (appned allows only at ends)
print(a1)
# insert 6,7 between 3rd and 4th element
a2 = np.insert(a1, 3, [6,7])
print(a2)

[100   2   3   4  60  20]
[100   2   3   6   7   4  60  20]


In [77]:
# Inserting for multio dimensional
print(d)

# Insert a 2nd row of element 390, 440, 660
d1 = np.insert(d, 1, [[390,440, 660], [44, 33, 22]], 0)
print(d1)

d2 = np.insert(d, 1, 3, 1)
print(d2)


[[  1   2   3]
 [  4   5   6]
 [  7 100   9]]
[[  1   2   3]
 [390 440 660]
 [ 44  33  22]
 [  4   5   6]
 [  7 100   9]]
[[  1   3   2   3]
 [  4   3   5   6]
 [  7   3 100   9]]
