## Key Points
- Assigning a sliced value of an array does not create a new obj, but only a refrence to part of it.
- To copy need to use copy() function

In [1]:
import numpy as np

In [4]:
d = np.array([[10,20,30,40,50], [100,200,300,400,500], [1000,2000,3000,4000,5000], [10000,20000,30000,40000,50000]])
print(d)

[[   10    20    30    40    50]
 [  100   200   300   400   500]
 [ 1000  2000  3000  4000  5000]
 [10000 20000 30000 40000 50000]]


In [6]:
z = d[1:,2:]
print(z)

[[  300   400   500]
 [ 3000  4000  5000]
 [30000 40000 50000]]


In [8]:
d2 = np.arange(20).reshape(4,5)
print(d2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [11]:
x = d[:3,:3]
print(x)

[[  10   20   30]
 [ 100  200  300]
 [1000 2000 3000]]


In [13]:
y = d[2, :]
print(y)

[1000 2000 3000 4000 5000]


In [16]:
print(d)
x = d[:,3] # For this is get a one dimensinal (rank 1) array
print(x)

[[   10    20    30    40    50]
 [  100   200   300   400   500]
 [ 1000  2000  3000  4000  5000]
 [10000 20000 30000 40000 50000]]
[   40   400  4000 40000]


In [18]:
#To get rank 2 for the above
x = d[:, 3:4]
print(x)

[[   40]
 [  400]
 [ 4000]
 [40000]]


In [19]:
print(d)

[[   10    20    30    40    50]
 [  100   200   300   400   500]
 [ 1000  2000  3000  4000  5000]
 [10000 20000 30000 40000 50000]]


In [22]:
# Getting 3rd and 5th row
s = np.array([2,4])
print(d[:,s])

[[   30    50]
 [  300   500]
 [ 3000  5000]
 [30000 50000]]


In [24]:
# Getting 1st and 4 th row
s = np.array([0,3])
print(d[s,:])

[[   10    20    30    40    50]
 [10000 20000 30000 40000 50000]]


In [30]:
k = np.diag(d)
print(k)

[   10   200  3000 40000]


In [33]:
j = np.diag(d, k = 1)
print(j)
j = np.diag(d, k = -1)
print(j)

[   20   300  4000 50000]
[  100  2000 30000]


In [35]:
X = np.array([[1,2,3],[5,2,8],[1,2,3]])
print(X)

[[1 2 3]
 [5 2 8]
 [1 2 3]]


In [36]:
print(np.unique(X))

[1 2 3 5 8]
