In [19]:
import numpy as np
x = np.array([1,2,3])
print(x)

[1 2 3]


In [20]:
print(type(x))
print(x.shape)
print(x.dtype)

<class 'numpy.ndarray'>
(3,)
int32


In [21]:
st = np.array(['hello','massu', '5wordl'])
print(st.dtype)

<U6


In [22]:
r2 = np.array([[1,2,3], [2, 3, 4], [1,2, 4]])
print(r2)
print(r2.shape)
print(r2.dtype)

[[1 2 3]
 [2 3 4]
 [1 2 4]]
(3, 3)
int32


In [23]:
m = np.array([1,2,3.2])
print(m)
print(m.dtype)

[ 1.   2.   3.2]
float64


In [24]:
m1 = np.array([1,2, 3.4], dtype = np.int32)
print(m1)
print(m1.dtype)

[1 2 3]
int32


In [25]:
np.save('myf',r2)

In [26]:
l = np.load('myf.npy')
print(l)

[[1 2 3]
 [2 3 4]
 [1 2 4]]


## Creating Arrays using NP functions

In [28]:
# Zeros
z = np.zeros((4,3))
print(z)

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [31]:
# Ones
o = np.ones((2,10))
print(o)

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]


In [35]:
# full
f = np.full((4,4),2)
print(f)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


#### Identity Matrix
1. Always a SQuare
2. Has ones in its digonal

In [39]:
# eye
i = np.eye(4, dtype = np.int32)
print(i)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [46]:
# diag
d = np.diag([10, 12, 44])
print(d)

[[10  0  0]
 [ 0 12  0]
 [ 0  0 44]]


In [50]:
# arange
ra = np.arange(10)
print(ra)
ra2 = np.arange(5, 10, 2)
print(ra2)


[0 1 2 3 4 5 6 7 8 9]
[5 7 9]


In [54]:
# Use linspace() for floats
fl = np.linspace(5, 10, 100)
print(fl)

[  5.           5.05050505   5.1010101    5.15151515   5.2020202
   5.25252525   5.3030303    5.35353535   5.4040404    5.45454545
   5.50505051   5.55555556   5.60606061   5.65656566   5.70707071
   5.75757576   5.80808081   5.85858586   5.90909091   5.95959596
   6.01010101   6.06060606   6.11111111   6.16161616   6.21212121
   6.26262626   6.31313131   6.36363636   6.41414141   6.46464646
   6.51515152   6.56565657   6.61616162   6.66666667   6.71717172
   6.76767677   6.81818182   6.86868687   6.91919192   6.96969697
   7.02020202   7.07070707   7.12121212   7.17171717   7.22222222
   7.27272727   7.32323232   7.37373737   7.42424242   7.47474747
   7.52525253   7.57575758   7.62626263   7.67676768   7.72727273
   7.77777778   7.82828283   7.87878788   7.92929293   7.97979798
   8.03030303   8.08080808   8.13131313   8.18181818   8.23232323
   8.28282828   8.33333333   8.38383838   8.43434343   8.48484848
   8.53535354   8.58585859   8.63636364   8.68686869   8.73737374
   8.787878

In [57]:
# reshape()
s = np.array([1,2,3,4,5,6,7,8,9,10])
rs = np.reshape(s, (2,5))
print(rs)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [69]:
# appending functions
ap = np.linspace(10, 12, 20, endpoint=False).reshape((5,4))
print(ap)

[[ 10.   10.1  10.2  10.3]
 [ 10.4  10.5  10.6  10.7]
 [ 10.8  10.9  11.   11.1]
 [ 11.2  11.3  11.4  11.5]
 [ 11.6  11.7  11.8  11.9]]


In [72]:
# random arrays
rd = np.random.random((10, 10))
print(rd)

[[ 0.12635332  0.1437065   0.42710535  0.57130691  0.79967369  0.2796757
   0.88978325  0.96634261  0.5848463   0.93878284]
 [ 0.98619693  0.24475692  0.06196604  0.98140571  0.53745133  0.06144683
   0.75920925  0.40806801  0.34002924  0.4169732 ]
 [ 0.26160428  0.92184552  0.8192104   0.76497187  0.19494703  0.98615393
   0.48611916  0.7932948   0.05378206  0.37214504]
 [ 0.39473715  0.49450867  0.8189834   0.18905803  0.25863984  0.62130828
   0.25240559  0.8695379   0.01984054  0.14436209]
 [ 0.22476143  0.06409294  0.71534047  0.16976783  0.66063284  0.28926756
   0.94341182  0.91034586  0.04582831  0.69444938]
 [ 0.631449    0.81498447  0.27249638  0.47660423  0.83265547  0.58083069
   0.87313052  0.94497742  0.81055471  0.61381408]
 [ 0.39156815  0.4007198   0.08773852  0.77864693  0.6237505   0.16652942
   0.84485534  0.16163743  0.23379942  0.39860726]
 [ 0.31150567  0.28137114  0.64070258  0.78191462  0.06497921  0.16587213
   0.05764019  0.4662625   0.64892806  0.07198279]
 

In [76]:
# random ints
ri = np.random.randint(10, 40,(4,4))
print(ri)

[[12 36 23 20]
 [22 24 38 23]
 [39 24 33 22]
 [32 34 30 29]]


In [77]:
# ranodom normal distributed array
n = np.random.normal(0, 0.1, size=(100,100))
print(n)

[[-0.04940448  0.1218179   0.00639089 ...,  0.08863033 -0.13671299
   0.04431478]
 [-0.13221902  0.13624765 -0.15122393 ...,  0.07695119  0.02064121
   0.16556368]
 [ 0.11899288  0.06604737 -0.08028968 ..., -0.05663345 -0.0336464
   0.00380134]
 ..., 
 [-0.00420346  0.02824846 -0.12873387 ...,  0.0341942   0.14047198
   0.17058198]
 [-0.06728304  0.22022851 -0.09006495 ...,  0.11693577  0.08345311
   0.19329596]
 [ 0.0543925  -0.02607321  0.01987511 ..., -0.12278481  0.06220996
   0.0435084 ]]
